services:
  postgres:
    image: postgres:latest
    container_name: soa
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soa
    restart: unless-stopped
  starship-service-1:
    image: bulat/second
    container_name: starship-service-1
    ports:
      - 8081:8081